name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx ng lint
